services:
  users_db:
    container_name: users_db
    build: ./infra/db/users
    ports:
      - 5432:5432
    volumes:
      - users_data:/var/lib/postgresql
    networks:
      - users_network

  analytics_db:
    container_name: analytics_db
    build: ./infra/db/analytics
    ports:
      - 5433:5432
    volumes:
      - analytics_data:/var/lib/postgresql
    networks:
      - analytics_network
      - event_driven

  shortener_db:
    container_name: shortener_db
    build: ./infra/db/shortener
    ports:
      - 5434:5432
    volumes:
      - shortener_data:/var/lib/postgresql
    networks:
      - shortener_network
      - event_driven

  rabbit:
    container_name: rabbit
    build: ./infra/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - event_driven

  shortener_service:
    container_name: shortener_service
    build: ./backend/shortener_service
    ports:
      - 8001:8000
    networks:
      - event_driven
      - shortener_network
    depends_on:
      shortener_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  analytics_worker:
    container_name: analytics_worker
    build: ./backend/analytics_worker
    networks:
      - event_driven
      - analytics_network
    depends_on:
      analytics_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  analytics_service:
    container_name: analytics_service
    build: ./backend/analytics_service
    ports:
      - 8002:8000
    networks:
      - event_driven
      - analytics_network
    depends_on:
      analytics_db:
        condition: service_healthy

networks:
  users_network:
    driver: bridge
  analytics_network:
    driver: bridge
  shortener_network:
    driver: bridge
  event_driven:
    driver: bridge

volumes:
  users_data:
  analytics_data:
  shortener_data:
