services:
  analytics_db:
    container_name: analytics_db
    build: ./infra/db/analytics
    volumes:
      - analytics_data:/var/lib/postgresql
    networks:
      - analytics_network
      - event_driven

  shortener_db:
    container_name: shortener_db
    build: ./infra/db/shortener
    volumes:
      - shortener_data:/var/lib/postgresql
    networks:
      - shortener_network
      - event_driven

  rabbit:
    container_name: rabbit
    build: ./infra/rabbitmq
    networks:
      - event_driven

  redis_cache:
    build: ./infra/redis
    networks:
      - shortener_network

  users_service:
    container_name: users_service
    build: ./backend/users_service
    networks:
      - shortener_network
      - analytics_network
      - app_network
    depends_on:
      shortener_db:
        condition: service_healthy

  shortener_service:
    container_name: shortener_service
    build: ./backend/shortener_service
    networks:
      - event_driven
      - shortener_network
      - app_network
    depends_on:
      shortener_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  analytics_worker:
    container_name: analytics_worker
    build: ./backend/analytics_worker
    networks:
      - event_driven
      - analytics_network
    depends_on:
      analytics_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  analytics_service:
    container_name: analytics_service
    build: ./backend/analytics_service
    networks:
      - event_driven
      - analytics_network
      - app_network
    depends_on:
      analytics_db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - app_network

    depends_on:
      - shortener_service
      - analytics_service
      - users_service

networks:
  app_network:
    driver: bridge
  analytics_network:
    driver: bridge
  shortener_network:
    driver: bridge
  event_driven:
    driver: bridge

volumes:
  analytics_data:
  shortener_data:
